import type { Employee } from './types'

export const mockEmployeesData: Employee[] = [
  {
    id: 'emp-1',
    name: 'Alice Admin',
    email: 'alice@zordr.com',
    roleId: 'role-1',
    role: 'Super Admin',
    department: 'engineering',
    status: 'active',
    lastActiveAt: '2026-10-05T18:00:00Z',
  },
  {
    id: 'emp-2',
    name: 'Bob Finance',
    email: 'bob@zordr.com',
    roleId: 'role-2',
    role: 'Finance Executive',
    department: 'finance',
    status: 'active',
    lastActiveAt: '2026-10-05T17:30:00Z',
  },
  {
    id: 'emp-3',
    name: 'Carol Support',
    email: 'carol@zordr.com',
    roleId: 'role-3',
    role: 'Support Executive',
    department: 'support',
    status: 'active',
    lastActiveAt: '2026-10-05T16:15:00Z',
  },
  {
    id: 'emp-4',
    name: 'Dave Marketer',
    email: 'dave@zordr.com',
    roleId: 'role-4',
    role: 'Marketing Executive',
    department: 'marketing',
    status: 'active',
    lastActiveAt: '2026-10-04T12:00:00Z',
  },
  {
    id: 'emp-5',
    name: 'Eve Ops',
    email: 'eve@zordr.com',
    roleId: 'role-5',
    role: 'Operations Manager',
    department: 'operations',
    status: 'active',
    lastActiveAt: '2026-10-05T09:00:00Z',
  },
  {
    id: 'emp-6',
    name: 'Frank Newguy',
    email: 'frank@zordr.com',
    roleId: 'role-3',
    role: 'Support Executive',
    department: 'support',
    status: 'invited',
    lastActiveAt: null,
  },
  {
    id: 'emp-7',
    name: 'Grace Leaver',
    email: 'grace@zordr.com',
    roleId: 'role-4',
    role: 'Marketing Executive',
    department: 'marketing',
    status: 'inactive',
    lastActiveAt: '2026-09-15T10:00:00Z',
  },
  {
    id: 'emp-8',
    name: 'Hank Ops',
    email: 'hank@zordr.com',
    roleId: 'role-5',
    role: 'Operations Manager',
    department: 'operations',
    status: 'active',
    lastActiveAt: '2026-10-05T14:20:00Z',
  },
  {
    id: 'emp-9',
    name: 'Ivy Finance',
    email: 'ivy@zordr.com',
    roleId: 'role-2',
    role: 'Finance Executive',
    department: 'finance',
    status: 'invited',
    lastActiveAt: null,
  },
  {
    id: 'emp-10',
    name: 'Jack Tech',
    email: 'jack@zordr.com',
    roleId: 'role-1',
    role: 'Super Admin',
    department: 'engineering',
    status: 'active',
    lastActiveAt: '2026-10-03T11:11:00Z',
  },
  {
    id: 'emp-11',
    name: 'Karen Support',
    email: 'karen@zordr.com',
    roleId: 'role-3',
    role: 'Support Executive',
    department: 'support',
    status: 'active',
    lastActiveAt: '2026-10-05T13:45:00Z',
  },
  {
    id: 'emp-12',
    name: 'Leo Support',
    email: 'leo@zordr.com',
    roleId: 'role-3',
    role: 'Support Executive',
    department: 'support',
    status: 'inactive',
    lastActiveAt: '2026-08-20T16:00:00Z',
  },
]
